### PR TITLE
Update 0 14

### PR DESCRIPTION
**Pull request by srghma**
this pr also fixes https://github.com/purescript/package-sets/issues/805

required dep https://github.com/purescript-codegen/purescript-ps-cst/pull/25/

@toastal could you check, please :)

if all is fine - I will update org and repo name

also, I hope you dont have a problem if I merge 0.14 update

USERS SHOULD EXECUTE

```
sd -s 'import GraphQLClient' 'import Dillonkearns.GraphQLClient' $(fd --type f . .)
```

P.S.

useful commands

```
sd 'Data.Generic.Rep.Show' 'Data.Show.Generic' $(fd --no-ignore --hidden --type f .purs .)
sd 'Data.Generic.Rep.Eq' 'Data.Eq.Generic' $(fd --no-ignore --hidden --type f .purs .)
sd 'Data.Generic.Rep.Ord' 'Data.Ord.Generic' $(fd --no-ignore --hidden --type f .purs .)
sd 'Data.Argonaut.Decode.Generic.Rep' 'Data.Argonaut.Decode.Generic' $(fd --no-ignore --hidden --type f .purs .)
sd 'Data.Argonaut.Encode.Generic.Rep' 'Data.Argonaut.Encode.Generic' $(fd --no-ignore --hidden --type f .purs .)
sd 'Data.Char.Unicode' 'Data.String.Unicode' $(fd --no-ignore --hidden --type f .purs .)
sd 'Data.Bifunctor.Wrap' 'Data.Functor.Wrap' $(fd --no-ignore --hidden --type f .purs .)
sd '\# Type' 'Row Type' $(fd --no-ignore --hidden --type f .purs .)
sd 'RowList\) ' 'RowList Type) ' $(fd --no-ignore --hidden --type f .purs .)
sd ', kind ([A-Z])' ', $1' $(fd --no-ignore --hidden --type f .purs .)
sd '\( kind ([A-Z])' '( $1' $(fd --no-ignore --hidden --type f .purs .)
sd -s 'import Global.Unsafe (unsafeEncodeURI)' 'import JSURI (encodeURI)' $(fd --no-ignore --hidden --type f .purs .)
sd -s 'import Global.Unsafe (unsafeEncodeURIComponent, unsafeDecodeURIComponent)' 'import JSURI (encodeURIComponent, decodeURIComponent)' $(fd --no-ignore --hidden --type f .purs .)
```

I'm also using https://github.com/srghma/my-purescript-package-sets/blob/master/mypackages.dhall

### CODE REVIEW

**Comment by toastal** [comment]
Are you sure you want to name this after someone who didn't write it? He's building tooling for sale around the Elm ecosystem and he may not want something he didn't built out there like this.

**Comment by toastal** [comment]
Also, PureScript 0.14.x is still in release candidate, and I don't think I'll be bothering to test until that's out because of time.

**Comment by srghma** [comment]
> Are you sure you want to name this after someone who didn't write it? 

It was @dillonkearns idea to use [`Scope__xxx`s](https://github.com/purescript-graphql-client/purescript-graphql-client/blob/d7d79ffc571e115e0ef01601c3feed5133021c81/src/GraphQLClient/Implementation.purs#L18-L22), and also [our `SelectorSet`](https://github.com/purescript-graphql-client/purescript-graphql-client/blob/d7d79ffc571e115e0ef01601c3feed5133021c81/src/GraphQLClient/Implementation.purs#L75-L89) is very similar to his

we could name it:
- https://github.com/purescript-dillonkearns-graphql-client/purescript-dillonkearns-graphql-client and `GraphQLClient` to `Dillonkearns.GraphQLClient` (this proposal)
- https://github.com/purescript-elm-graphql-client/purescript-elm-graphql-client
- https://github.com/purescript-graphql-client-scoped/purescript-graphql-client-scoped
- https://github.com/purescript-graphqlclient/purescript-graphqlclient and leave the module name `GraphQLClient`, since https://github.com/OxfordAbstracts/purescript-graphql-client have `GraphQL.Client`

> He's building tooling for sale around the Elm ecosystem and he may not want something he didn't built out there like this.

@dillonkearns, we have built a purescript library inspired by yours https://github.com/dillonkearns/elm-graphql

We have named this library https://github.com/purescript-graphql-client/purescript-graphql-client

But were late with publishing it to our "package registry" https://github.com/purescript/package-sets and other library took our name https://github.com/OxfordAbstracts/purescript-graphql-client

Now we are forced to rename it (but maybe this is good to make a unique name)

@dillonkearns, can we name this lib after you https://github.com/purescript-dillonkearns-graphql-client/purescript-dillonkearns-graphql-client ?

**Comment by dillonkearns** [comment]
Hello, thanks for asking. I'd like to leave my name out since it's not a project that I'm involved with, so please don't use my name in the project naming or NPM package name.

I would love a shout out in the README or docs that says `dillonkearns/elm-graphql` is inspiration. And you are more than welcome to use any design ideas or direct code from the project! But I don't think using my name in the library name makes sense and it would lead to confusion. Thank you!

**Comment by srghma** [comment]
@dillonkearns it's already in readme

**Comment by dillonkearns** [comment]
Awesome, thanks for the readme shout out 😄

**Comment by srghma** [comment]
@toastal I think https://github.com/purescript-graphqlclient/purescript-graphqlclient would organically fit already existing module name `GraphQLClient`

**Comment by toastal** [comment]
GraphCueEl? GQLClient?

**Comment by srghma** [comment]
> GraphCueEl

too ... spanish)

> GQLClient

yes, good, let it be the second option, I will try to rename as I proposed before and submit to package-sets

**Comment by dillonkearns** [comment]
It seems like "dillonkearns" is still showing up in the code now on the master branch? Could we make sure that all those references are removed?

https://github.com/purescript-graphqlclient/purescript-graphqlclient/blob/6c36a6315dde88df474dd8da4585a005c6d798c7/generator/GraphQLClientGenerator/MakeModule/Lib/Fragments.purs

**Comment by srghma** [comment]
@dillonkearns yes, yes, it was WIP, no mentions, removed

**Comment by toastal** [comment]
I've not been in a state to upgrade to v0.14 yet on our codebase. Halogen was just upgraded.

**Comment by srghma** [comment]
@toastal sorry for this, you can use pre merge commit https://github.com/purescript-graphqlclient/purescript-graphqlclient/commit/d7d79ffc571e115e0ef01601c3feed5133021c81

Tell me if I need something to do

**Pull request merged**
